AllCops:
  TargetRubyVersion: 2.3

Style/GlobalVars:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 130

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false