AllCops:
  TargetRubyVersion: 2.3

Style/GlobalVars:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 130
